name: gh-pages
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx parcel build --dist-dir dist page\index.html
      - uses: actions/upload-artifact@v2
        with:
          path: dist
